// Generates supabase/seed.sql from the site's current sample content.
// Run from the repo root:  node --experimental-strip-types supabase/generate-seed.ts
import { writeFileSync } from 'node:fs';
import {
  mockCategories, mockStories, mockMagazineIssues, mockInterviews, mockTestimonials, mockFAQs,
} from '../client/src/data/mockData.ts';

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};
const arr = (xs: string[]) => `array[${xs.map(q).join(', ')}]::text[]`;
const isoDate = (s: string) => new Date(`${s} 12:00 UTC`).toISOString().slice(0, 10);
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

// Story content in the sample data is indented; strip that so paragraphs render cleanly
const cleanContent = (s: string) => s.split('\n').map((l) => l.trim()).join('\n').replace(/\n{3,}/g, '\n\n').trim();

const out: string[] = [
  '-- Sample content for The Impact Ledger (generated by supabase/generate-seed.ts).',
  '-- Run once after schema.sql. Re-running skips rows that already exist.',
  '',
];

mockCategories.forEach((c, i) => out.push(
  `insert into public.categories (name, slug, description, icon_name, sort_order) values (${q(c.name)}, ${q(c.slug)}, ${q(c.description)}, ${q(c.iconName)}, ${i}) on conflict (slug) do nothing;`,
));
out.push('');

mockStories.forEach((s) => out.push(
  `insert into public.stories (slug, title, summary, content, category, author_name, author_role, author_avatar, featured_image, published_date, reading_time, is_featured, is_editors_pick, status) values (${[
    s.slug, s.title, s.summary, cleanContent(s.content), s.category, s.author.name, s.author.role, s.author.avatar,
    s.featuredImage].map(q).join(', ')}, ${q(isoDate(s.publishedDate))}, ${q(s.readingTime)}, ${q(!!s.isFeatured)}, ${q(!!s.isEditorsPick)}, 'published') on conflict (slug) do nothing;`,
));
out.push('');

out.push('-- Magazines have no natural unique key, so only seed them into an empty table');
out.push('do $$ begin if not exists (select 1 from public.magazine_issues) then');
mockMagazineIssues.forEach((m) => {
  const release = `${m.year}-${String(MONTHS.indexOf(m.month) + 1).padStart(2, '0')}-01`;
  out.push(
    `  insert into public.magazine_issues (issue_number, title, month, year, release_date, cover_image, editors_note, featured_articles, is_trending, is_most_read, status) values (${[
      m.issueNumber, m.title, m.month, m.year, release, m.coverImage, m.editorsNote].map(q).join(', ')}, ${arr(m.featuredArticles ?? [])}, ${q(!!m.isTrending)}, ${q(!!m.isMostRead)}, 'published');`,
  );
});
out.push('end if; end $$;', '');

out.push('do $$ begin if not exists (select 1 from public.interviews) then');
mockInterviews.forEach((iv) => out.push(
  `  insert into public.interviews (title, interviewee, position, organization, photo, quote, highlights, questions, status) values (${[
    iv.title, iv.interviewee, iv.position, iv.organization, iv.photo, iv.quote].map(q).join(', ')}, ${arr(iv.highlights)}, ${q(JSON.stringify(iv.questions))}::jsonb, 'published');`,
));
out.push('end if; end $$;', '');

out.push('do $$ begin if not exists (select 1 from public.testimonials) then');
mockTestimonials.forEach((t, i) => out.push(
  `  insert into public.testimonials (quote, author, role, organization, sort_order) values (${[t.quote, t.author, t.role, t.organization].map(q).join(', ')}, ${i});`,
));
out.push('end if; end $$;', '');

out.push('do $$ begin if not exists (select 1 from public.faqs) then');
mockFAQs.forEach((f, i) => out.push(
  `  insert into public.faqs (question, answer, sort_order) values (${q(f.question)}, ${q(f.answer)}, ${i});`,
));
out.push('end if; end $$;', '');

writeFileSync(new URL('./seed.sql', import.meta.url), out.join('\n'));
console.log(`seed.sql written: ${mockStories.length} stories, ${mockMagazineIssues.length} issues, ${mockFAQs.length} FAQs`);
